version: '3.8'

services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Redacted
      POSTGRES_USER: Redacted
      POSTGRES_PASSWORD: Redacted
      POSTGRES_HOST_AUTH_METHOD: Redacted
  meilisearch:
    image: getmeili/meilisearch:v1.5.0
    restart: on-failure
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: Redacted
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 107374182400
