name: Rust CI Build and Dist

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
        restore-keys: |
          ${{ runner.os }}-cargo-registry

    - name: Cache Cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
        restore-keys: |
          ${{ runner.os }}-cargo-index

    - name: Install dependencies
      run: |
        cd api
        cargo install --path .

    - name: Build
      run: cargo build --release

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry
        restore-keys: |
          ${{ runner.os }}-cargo-registry

    - name: Cache Cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index
        restore-keys: |
          ${{ runner.os }}-cargo-index

    - name: Install dependencies
      run: |
        cd api
        cargo install --path .

    - name: Generate and submit dependency graph
      run: |
        cargo audit --json > audit.json
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Content-Type: application/json" \
             -d @audit.json \
             https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
